- import_tasks: packages_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: packages_darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: packages_pip.yml

- import_tasks: sources.yml

- import_tasks: configs.yml
