- name: setup_system [darwin] | install requirements [system]
  package: name="{{ item }}"
  with_items: "{{ system_requirements }}"

- name: setup_system [darwin] | install requirements [python]
  package: name="{{ item }}"
  with_items: "{{ python_requirements }}"
