#################
# Ansible options
#################

ansible_requirements_debian:
  - aptitude
  - git
  - python3
  - python3-apt
  - python3-pexpect
  - python3-pip

ansible_python_interpreter: "/usr/bin/env python3"

################
# System options
################

system_requirements:
  - tmux

system_requirements_debian:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - locales
  - software-properties-common

  # Build dependencies.
  - autoconf
  - automake
  - autotools-dev
  - binutils
  - gcc
  - g++
  - make
  - pkg-config
  - sed

################
# Python options
################

python_requirements:
  - python3

  # To support remote debugging.
  - rlwrap
  - telnet

  # Testing tools.
  - tox

python_requirements_debian:
  - python3-apt
  - python3-pip
  - python3-venv

  # Build dependencies.
  - build-essential
  - gcc
  - libffi-dev
  - libssl-dev
  - python3-dev

  # To build python with pyevn.
  - libbz2-dev
  - liblzma-dev
  - libreadline-dev
  - libsqlite3-dev

  # To support MySQL.
  - libmysqlclient-dev

python_requirements_pip:
  - setuptools
  - virtualenv
  - wheel

  # Remote debugging based on pdb.
  - rpdb

python_requirements_sources:
  - name: pyenv
    repo: https://github.com/pyenv/pyenv.git
    location: "{{ ansible_env.HOME }}/.pyenv"

##############
# Ruby options
##############

ruby_requirements_darwin:
  - rbenv

#############
# Vim options
#############

vim_requirements_debian:
  - silversearcher-ag

vim_requirements_darwin:
  - the_silver_searcher
